<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>1.4.3</Version>
    <Description>Provides support for declaring covariant and contravariant generic parameters for languages that lack native support, like F#.</Description>
    <Authors>Theodore Tsirpanis</Authors>
    <Copyright>Copyright © Theodore Tsirpanis. Licensed under the MIT License.</Copyright>
    <PackageReleaseNotes>Covarsky was updated to use Sigourney 0.5.0.

Diagnostics emitted by Covarsky now include a help link.</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/teo-tsirpanis/Covarsky</PackageProjectUrl>
    <PackageTags>covariance;contravariance;fsharp;sigourney</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>
  <PropertyGroup Label="Dependency packing">
    <GenerateDependencyFile>true</GenerateDependencyFile>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    <BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
    <None Include="build/**" Pack="true" PackagePath="build" />
    <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.2.25" PrivateAssets="all" />
    <PackageReference Include="Sigourney" Version="0.5.0" PrivateAssets="all" Publish="true" />
    <PackageReference Include="Sigourney.Build" Version="0.5.0" />
  </ItemGroup>
  <Target
      Name="AddBuildDependencyFileToBuiltProjectOutputGroupOutput"
      BeforeTargets="BuiltProjectOutputGroup">
    <ItemGroup>
      <BuiltProjectOutputGroupOutput
        Include="$(ProjectDepsFilePath)"
        TargetPath="$(ProjectDepsFileName)"
        FinalOutputPath="$(ProjectDepsFilePath)" />
    </ItemGroup>
  </Target>
  <Target
    Name="CopyProjectReferencesToPackage"
    DependsOnTargets="ResolveReferences">
    <ItemGroup>
        <BuildOutputInPackage
            Include="@(ReferenceCopyLocalPaths)"
            TargetPath="%(ReferenceCopyLocalPaths.DestinationSubPath)" />
    </ItemGroup>
  </Target>
</Project>
