name: Test
on:
  push:
    branches: [ mainstream ]
  pull_request:
    branches: [ mainstream ]
jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    timeout-minutes: 30
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run the test script
        shell: pwsh
        run: ./test.ps1
      - name: Upload the failed test logs
        uses: actions/upload-artifact@v4
        with:
          name: testlogs-${{ matrix.os }}
          path: ./test-logs/
        if: ${{ failure() }}
